# Base Image
FROM node:alpine

# Correções erro cache
USER node
RUN mkdir -p /home/node/app

# Working directory
WORKDIR '/home/node/app'

# Copy package.json to current WORKDIR
# COPY package.json .
COPY --chown=node:node ./package.json ./

# Install dependencies
RUN npm install

# Copy everything over to project directory
# COPY . .
COPY --chown=node:node ./ ./

# Run the project
CMD [ "npm", "run", "start" ]
